MorningBank/Controllers/BankingController.cs
using MorningBank.BusinessLayer;
using MorningBank.Models.DomainModels;
using MorningBank.Models.ViewModels;
using MorningBank.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MorningBank.Controllers
{
    [Authorize]
    public class BankingController : Controller
    {
        public ActionResult TransferCheckingToSaving()
        {
            TransferCToSModel tcs = new TransferCToSModel();
            UserInfo ui = CookieFacade.USERINFO;
            IBusinessBanking ibank = GenericFactory<Business, IBusinessBanking>.GetInstance();
            tcs.CheckingBalance = ibank.GetCheckingBalance(ui.CheckingAcccountNumber);
            tcs.SavingBalance = ibank.GetSavingBalance(ui.SavingAccountNumber);
            tcs.Amount = 5;
            ViewBag.Message = "";
            return View(tcs);
        }
        [HttpPost]
        public ActionResult TransferCheckingToSaving(TransferCToSModel tcs)
        {
            IBusinessBanking ibank = GenericFactory<Business, IBusinessBanking>.GetInstance();
            UserInfo ui = CookieFacade.USERINFO;
            try
            {
                if (ModelState.IsValid)
                {
                    bool ret = ibank.TransferCheckingToSaving(ui.CheckingAcccountNumber, ui.SavingAccountNumber, tcs.Amount);
                    if (ret == true)
                    {
                        ViewBag.Success = true;
                        ViewBag.Message = "Transfer successful..";
                        ModelState.Clear(); // otherwise, textbox will display the old amount
                        tcs.Amount = 0;
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Success = false;
                ViewBag.Message = ex.Message;
            }
            tcs.CheckingBalance = ibank.GetCheckingBalance(ui.CheckingAcccountNumber);
            tcs.SavingBalance = ibank.GetSavingBalance(ui.SavingAccountNumber);
            return View(tcs);
        }
        public ActionResult TransferHistory()
        {
            IBusinessBanking ibank = GenericFactory<Business, IBusinessBanking>.GetInstance();
            UserInfo ui = CookieFacade.USERINFO;
            List<Models.DomainModels.TransactionHistoryModel> THList = ibank.GetTransactionHistory(ui.CheckingAcccountNumber);
            Models.ViewModels.TransactionHistoryModel thm = new Models.ViewModels.TransactionHistoryModel();

            return View(THList);
        }
    }
}

MorningBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MYBank</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MYBank", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>
                        @Html.ActionLink("TransferCToS", "TransferCheckingToSaving", "Banking")
                    </li>
                    <li>
                        @Html.ActionLink("Transfer History", "TransferHistory", "Banking")
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MYBank</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>